#!/bin/sh
name() {
    echo "$NAME"
}

hook() { 
    args=("$@")
    SCR=${args[1]}
    if [ -f $SCR ] || [ ! -d $SCR ]; then
        SCRPATH=$( cd "$(dirname "$SCR")" ; pwd -P )/"$(basename "$SCR")" #ABS
        ln -sf $SCRPATH "$HOME/.fnkeyscr"
        exit
    fi
    echo "usage: fnkeysh hook <file>"
}

if [ -f ~/.fnkeyscr ]; then
    if [[ -z "$1" ]]; then
        readlink "$HOME/.fnkeyscr" 
        exit 0
    fi

    . "$HOME/.fnkeyscr"
fi

$1
